### ISSUE TITLE
DIGITALTWIN - add a description page for each solutions

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/www_threefold_twin#33]
- [x]  create .md files with description for each solution
- [x] make cards clickable opening description page in same tab (issue: #48)

<img width="1181" alt="Screenshot 2021-02-28 at 15 00 49" src="https://user-images.githubusercontent.com/20182572/109419493-6b97ba00-79d6-11eb-8dd3-6e9b6be69c7b.png">

**Comment by samtaggart** [comment]
- Had a discussion with Zia and Alex about this.
- Alex will follow up with the Jimber team to get a list of features per experience.
- Zia will come up with a template we can apply to each page.

- I think we should also have a simple graphic per experience explaining what is happening in the background vs what happens currently – e.g. a video connection going between peers rather than going to a data center first

**Comment by nbabenko** [comment]
considered as top prio right now

**Comment by nbabenko** [comment]
text template is put to the document: https://secure.threefold.me/pad/#/2/pad/edit/NiMhcN6gp+0wnD2jVBTdZDqm/

**Comment by samtaggart** [comment]
This will likely not be finished this sprint as we didn't get the information necessary quickly enough. Will update today on what's realistic after we meet with Zia.

**Comment by AlexandreHannelas** [comment]
Sacha and I worked on the file: https://secure.threefold.me/pad/#/2/pad/edit/NiMhcN6gp+0wnD2jVBTdZDqm/

**Comment by samtaggart** [comment]
Offered feedback!

**Comment by AlexandreHannelas** [comment]
AI file sent to @Vilnite
